### ISSUE TITLE
orphaned child processes remain when marking task as failed

### ISSUE THREAD

**Issue by 3pm** [damavis/airflow-pentaho-plugin#39]
Hello,
After we mark running Airflow pentaho task's state as Failed, Airflow cannot kill related child procesess and they stay as orphaned and only can be killed later manually from console. It happens, that Airflow kills parent, but not child processes.
Expected behavior is Airflow kills parent an child processes automatically.
It doesn't happen as seen in logs:
`[2025-09-19T10:28:42.147+0300] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-09-19T10:28:42.147+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-09-19T10:28:42.151+0300] {process_utils.py:132} INFO - Sending 15 to group 208397. PIDs of all processes in the group: [208406, 208407, 208411, 208459, 208397]
[2025-09-19T10:28:42.152+0300] {process_utils.py:87} INFO - Sending the signal 15 to group 208397
[2025-09-19T10:28:42.152+0300] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-19T10:28:42.184+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-19T10:28:42.216+0300] {process_utils.py:80} INFO - Process psutil.Process(pid=208397, status='terminated', exitcode=0, started='10:25:34') (208397) terminated with exit code 0
[2025-09-19T10:28:45.295+0300] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-09-19T10:29:42.181+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=208411, name='spoon.sh', status='sleeping', started='10:25:34') did not respond to SIGTERM. Trying SIGKILL
[2025-09-19T10:29:42.183+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=208406, name='bash', status='sleeping', started='10:25:34') did not respond to SIGTERM. Trying SIGKILL
[2025-09-19T10:29:42.183+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=208407, name='pan.sh', status='sleeping', started='10:25:34') did not respond to SIGTERM. Trying SIGKILL
[2025-09-19T10:29:42.183+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=208459, name='java', status='sleeping', started='10:25:34') did not respond to SIGTERM. Trying SIGKILL
[2025-09-19T10:29:42.183+0300] {process_utils.py:87} INFO - Sending the signal 9 to group 208397
[2025-09-19T10:29:42.183+0300] {process_utils.py:101} INFO - Sending the signal 9 to process 208397 as process group is missing.
[2025-09-19T10:30:42.215+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=208411, name='spoon.sh', status='sleeping', started='10:25:34') (208411) could not be killed. Giving up.
[2025-09-19T10:30:42.216+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=208406, name='bash', status='sleeping', started='10:25:34') (208406) could not be killed. Giving up.
[2025-09-19T10:30:42.216+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=208407, name='pan.sh', status='sleeping', started='10:25:34') (208407) could not be killed. Giving up.
[2025-09-19T10:30:42.216+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=208459, name='java', status='sleeping', started='10:25:34') (208459) could not be killed. Giving up.
`

I have a fix for it in: https://github.com/3pm/airflow-pentaho-plugin/tree/Orphan-child-fix#

But I'm not an expert and some modifications parts are AI suggested, so review an test is needed. I tested in local Airflow 2.10.3 instance, it seems fixed an issue.

**Comment by piffall** [comment]
Hi @3pm , I've just released the [v1.2.1](https://github.com/damavis/airflow-pentaho-plugin/releases/tag/1.2.1). That should take care of child processes that are not killed. Thanks to @egor-popov 

Hope this solves the problem.

**Comment by 3pm** [comment]
Tested. With airflow_pentaho_plugin-1.2.1 on linux Mint/Ubuntu. Unfortinately latest release doesn't fix this issue.
Steps to reproduce:
1. Create transformation that never ends e.g. generate rows.
2. Add it to Airflow and launch manually/schdeuled as transformation.
3. Mark task state as failed while it's running.
4. Airflow DAG tries to kill that batch process and fails. 
5. Pentaho process becames orphaned process (still running) in worker machine, and can be only killed via console.

**Comment by egor-popov** [comment]
Hi, @3pm! 
Do you have a message about trying to apply SIGKILL signal in that case of yours in Airflow logs? It should look like [this](https://github.com/damavis/airflow-pentaho-plugin/blob/6d3439c255912fde4b25c153ec35aa35d40f2919/airflow_pentaho/operators/kettle.py#L120)

**Comment by 3pm** [comment]
[2025-09-26T09:50:48.978+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=10937, name='pan.sh', status='sleeping', started='09:49:03') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T09:50:48.979+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=10989, name='java', status='sleeping', started='09:49:03') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T09:50:48.979+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=10941, name='spoon.sh', status='sleeping', started='09:49:03') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T09:50:48.980+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=10936, name='bash', status='sleeping', started='09:49:03') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T09:50:48.980+0300] {process_utils.py:87} INFO - Sending the signal 9 to group 10905
[2025-09-26T09:50:48.980+0300] {process_utils.py:101} INFO - Sending the signal 9 to process 10905 as process group is missing.
[2025-09-26T09:51:48.997+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=10937, name='pan.sh', status='sleeping', started='09:49:03') (10937) could not be killed. Giving up.
[2025-09-26T09:51:48.998+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=10989, name='java', status='sleeping', started='09:49:03') (10989) could not be killed. Giving up.
[2025-09-26T09:51:48.998+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=10941, name='spoon.sh', status='sleeping', started='09:49:03') (10941) could not be killed. Giving up.
[2025-09-26T09:51:48.998+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=10936, name='bash', status='sleeping', started='09:49:03') (10936) could not be killed. Giving up.

**Comment by 3pm** [comment]
There are another related problem as well. Airflow should kill batch processes if DAG timeout occuring as well. Currently this doesn't happen at all- there are even not killing attempts for timeouted tasks.
We encounter problems when some jobs/transformations stuck on db queries and not being killed due to timeout.

**Comment by piffall** [comment]
I've just released [1.2.2](https://github.com/damavis/airflow-pentaho-plugin/releases/tag/1.2.2), can you @3pm @egor-popov test this change.

**Comment by 3pm** [comment]
Wrapped into job, teh same behavior:
[2025-09-26T10:55:36.961+0300] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-26T10:55:36.998+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-26T10:55:37.635+0300] {process_utils.py:80} INFO - Process psutil.Process(pid=104095, status='terminated', exitcode=0, started='10:54:36') (104095) terminated with exit code 0
[2025-09-26T10:55:41.205+0300] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-09-26T10:56:36.995+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=104109, name='spoon.sh', status='sleeping', started='10:54:36') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T10:56:36.996+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=104104, name='bash', status='sleeping', started='10:54:36') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T10:56:36.996+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=104105, name='kitchen.sh', status='sleeping', started='10:54:36') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T10:56:36.996+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=104157, name='java', status='sleeping', started='10:54:36') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T10:56:36.996+0300] {process_utils.py:87} INFO - Sending the signal 9 to group 104095
[2025-09-26T10:56:36.996+0300] {process_utils.py:101} INFO - Sending the signal 9 to process 104095 as process group is missing.

**Comment by 3pm** [comment]
> I've just released [1.2.2](https://github.com/damavis/airflow-pentaho-plugin/releases/tag/1.2.2), can you [@3pm](https://github.com/3pm) [@egor-popov](https://github.com/egor-popov) test this change.

Thank you will test.

**Comment by 3pm** [comment]
Tested 1.2.2 the same behaviour, not being killed:
2025-09-26T12:11:39.605+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=213974, name='pan.sh', status='sleeping', started='12:09:38') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T12:11:39.607+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=214026, name='java', status='sleeping', started='12:09:38') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T12:11:39.607+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=213978, name='spoon.sh', status='sleeping', started='12:09:38') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T12:11:39.607+0300] {process_utils.py:150} WARNING - process psutil.Process(pid=213973, name='bash', status='sleeping', started='12:09:38') did not respond to SIGTERM. Trying SIGKILL
[2025-09-26T12:11:39.607+0300] {process_utils.py:87} INFO - Sending the signal 9 to group 213964
[2025-09-26T12:11:39.607+0300] {process_utils.py:101} INFO - Sending the signal 9 to process 213964 as process group is missing.
[2025-09-26T12:12:39.610+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=213974, name='pan.sh', status='sleeping', started='12:09:38') (213974) could not be killed. Giving up.
[2025-09-26T12:12:39.610+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=214026, name='java', status='sleeping', started='12:09:38') (214026) could not be killed. Giving up.
[2025-09-26T12:12:39.612+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=213978, name='spoon.sh', status='sleeping', started='12:09:38') (213978) could not be killed. Giving up.
[2025-09-26T12:12:39.613+0300] {process_utils.py:161} ERROR - Process psutil.Process(pid=213973, name='bash', status='sleeping', started='12:09:38') (213973) could not be killed. Giving up.

**Comment by piffall** [comment]
Sorry @3pm @egor-popov . I don't have a proper environment for testing end to end right now. I've just released a version where the `pre_execfn` is not used. Let me know if that works.

**Comment by 3pm** [comment]
Hello!
Tank you.
1. airflow_pentaho_plugin-1.2.3 does kill processes now if task is marked as failed.

2. But still have an issue, if task is timeouted, java processes remain running.
It seems that in that situation on_kill method is not called at all, according to the logs.
Not sure if this behavior is not an airflow configuration issue though or it should be done by plugin.

> [2025-09-29, 10:34:38 EEST] {taskinstance.py:340} ▼ Post task execution logs
[2025-09-29, 10:34:38 EEST] {local_task_job_runner.py:266} INFO - Task exited with return code 2
[2025-09-29, 10:34:38 EEST] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-29, 10:34:38 EEST] {local_task_job_runner.py:245} ▲▲▲ Log group end

**Comment by 3pm** [comment]
Checked Airflow, code. Timeout issue seems related to Airflow itself. In case of timeout, self.terminating is not set to True
This can be closed.
